import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useAccount, useDisconnect, useEnsAvatar, useEnsName } from 'wagmi'
import { useGetPointsQuery } from '../services/points'

const Map = dynamic(() => import('../components/Map/Map'), {
  ssr: false,
})
const WalletOptionsModal = dynamic(
  () => import('../components/WalletOptionsModal/WalletOptionsModal'),
  {
    ssr: false,
  }
)

export default function Home() {
  const { data: account } = useAccount()
  const { data: ensAvatar } = useEnsAvatar({ addressOrName: account?.address })
  const { data: ensName } = useEnsName({ address: account?.address })
  const { disconnect } = useDisconnect()
  const [isModalOpen, setModalOpen] = useState(false)
  const [isAccountVisible, setAccountVisibility] = useState(false)

  const {
    data: points,
    error: pointsError,
    isLoading: pointsIsLoading,
    refetch: pointsRefetch,
  } = useGetPointsQuery()

  useEffect(() => {
    if (account && isModalOpen) {
      setModalOpen(false)
    }
    if (account) {
      setAccountVisibility(true)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [account])

  const handleOnConnect = (address: string) => {
    alert(address)
    setAccountVisibility(true)
  }
  const handleDisconnect = () => {
    disconnect()
    setAccountVisibility(false)
  }

  return (
    <>
      <Head>
        <title>PayDece P2P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex flex-col items-center justify-center">
        <h1 className="text-6xl mb-8">PayDece P2P</h1>
        {isAccountVisible && (
          <div className="flex justify-center flex-col">
            <div className="mb-4 text-center">
              {ensAvatar && <img src={ensAvatar} alt="ENS Avatar" />}
              <div>
                {ensName ? `${ensName} (${account.address})` : account.address}
              </div>
              <div className="text-green-600">
                Connected to {account?.connector?.name}
              </div>
            </div>
            <button
              onClick={handleDisconnect}
              className="px-4 py-2 mx-2 rounded-full bg-blue-400"
            >
              Disconnect
            </button>
          </div>
        )}
        {!isAccountVisible && (
          <div className="flex justify-center">
            <button onClick={() => setModalOpen((prev) => !prev)}>
              Connect Wallet
            </button>
          </div>
        )}
        <WalletOptionsModal
          open={isModalOpen}
          setOpen={setModalOpen}
          onConnect={handleOnConnect}
        />

        <Map data={points} />
      </main>
    </>
  )
}
