import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import AddressBar from '../components/AddressBar/AddressBar'
import Header from '../components/Header/Header'
import Welcome from '../components/Welcome/Welcome'
import { useGetPointsQuery } from '../services/points'
import { TLocation } from '../types'

const Map = dynamic(() => import('../components/Map/Map'), {
  ssr: false,
})

export default function Home() {
  const [isWelcomeVisible, setWelcomeVisible] = useState(true)
  const [currentLocation, setCurrentLocation] = useState<TLocation['latLng']>({
    lat: -31.4173391,
    lng: -64.183319,
  })

  const {
    data: points,
    error: pointsError,
    isLoading: pointsIsLoading,
    refetch: pointsRefetch,
  } = useGetPointsQuery()

  useEffect(() => {
    let timeout = setTimeout(() => {
      setWelcomeVisible(false)
    }, 3000)

    return () => {
      clearTimeout(timeout)
    }
  }, [])

  return (
    <>
      <Head>
        <title>PayDece P2P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen relative flex flex-col items-center justify-center brand-gradient-vertical">
        <h1 className="text-6xl mb-8 hidden">PayDece P2P</h1>
        {isWelcomeVisible ? (
          <Welcome />
        ) : (
          <div className="absolute top-0 left-0 w-full z-10">
            <Header />
            <AddressBar onChange={(latLng) => setCurrentLocation(latLng)} />
          </div>
        )}
        <Map
          data={points}
          lat={currentLocation.lat}
          lng={currentLocation.lng}
        />
      </main>
    </>
  )
}
