import Head from "next/head";
import { useEffect, useState } from "react";
import {
  useAccount,
  useConnect,
  useDisconnect,
  useEnsAvatar,
  useEnsName
} from "wagmi";
import WalletOptionsModal from "../components/WalletOptionsModal/WalletOptionsModal";
import Map from "../components/Map/Map";

export default function Home() {
  const { data: account } = useAccount();
  const { data: ensAvatar } = useEnsAvatar({ addressOrName: account?.address });
  const { data: ensName } = useEnsName({ address: account?.address });
  const { disconnect } = useDisconnect();
  const [isModalOpen, setModalOpen] = useState(false);

  useEffect(() => {
    if (account) {
      setModalOpen(false);
    }
  }, [account]);

  return (
    <div>
      <Head>
        <title>PayDece P2P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex flex-col items-center justify-center">
        <h1 className="text-6xl mb-8">PayDece P2P</h1>

        {account ? (
          <div className="flex justify-center flex-col">
            <div className="mb-4 text-center">
              {ensAvatar && <img src={ensAvatar} alt="ENS Avatar" />}
              <div>
                {ensName ? `${ensName} (${account.address})` : account.address}
              </div>
              <div className="text-green-600">
                Connected to {account?.connector?.name}
              </div>
            </div>
            <button
              onClick={() => disconnect()}
              className="px-4 py-2 mx-2 rounded-full bg-blue-400"
            >
              Disconnect
            </button>
          </div>
        ) : (
          <>
            <div className="flex justify-center">
              <button onClick={() => setModalOpen((prev) => !prev)}>
                Connect Wallet
              </button>
              <WalletOptionsModal open={isModalOpen} setOpen={setModalOpen} />
            </div>
          </>
        )}

        <Map />
      </main>
    </div>
  );
}
