export const MarkerStyle = 'cursor-pointer filter drop-shadow-lg'
export const PopupContentStyle =
  'relative flex flex-col y-3 px-2 pt-2 pr-6 rounded-md w-64 filter drop-shadow-lg'
export const PopupCloseIconStyle = 'absolute top-2 right-2 cursor-pointer'
export const PopupTitleStyle = 'block font-bold text-black'
export const PopupSubTitleStyle = 'block text-gray-500'
export const LinksStyle = 'flex space-x-4 mt-3'
export const WhatsAppIconStyle = 'fill-current text-green-600'
export const LinkIconStyle = 'fill-current text-blue-600'
export const PointStyle = 'fill-current opacity-75'
export const UserPointStyle = 'fill-current text-[color:var(--primary)]'
